### ISSUE TITLE
Not getting encrypted output while trying to encrypt a number containing 0 in it.

### ISSUE THREAD

**Issue by rash039** [ivanakimov/hashids.php#100]
I am not getting output if number contains 0 in it.
Because of which i am unable to encrypt mobile numbers.

    use Hashids\Hashids;

    $hashids = new Hashids('My Project');
    echo $hashids->encode(1233603563); // no output

    echo "\n";

    $hashids = new Hashids('My Other Project');
    echo  $hashids->encode(123363563); // AJ78rq 

    echo "\n";

**Comment by vinkla** [comment]
> Do not use this library as a security tool and do not encode sensitive data. This is **not** an encryption library.

https://github.com/ivanakimov/hashids.php#readme

**Comment by rash039** [comment]
But this was a simple example of a string containing 0 within it.
I am not using any sensitive data.

What if my string contains 0?
