### ISSUE TITLE
encodeHex not taking letters

### ISSUE THREAD

**Issue by lifewcody** [ivanakimov/hashids.php#101]
MongoDB Object Id's not able to be encoded.

I tried using MongoDB Object Ids but they fail. I am using the latest version (2.0.4) (i upgraded from 2.0.3 to see if it would fix it). I am using encodeHex() but letters make it fail.

**Comment by lifewcody** [comment]
The following code from the readme fails:
```php
use Hashids\Hashids;

$hashids = new Hashids();

$id = $hashids->encodeHex('507f1f77bcf86cd799439011'); // y42LW46J9luq3Xq9XMly
$hex = $hashids->decodeHex($id); // 507f1f77bcf86cd799439011
```

In encodeHex() here is the print_r before it gets sent to encode

`Array ( [0] => 3.6998189572018E+14 [1] => 4.0114822182094E+14 ) `

It gets terminated here:

```php
foreach ($numbers as $number) {
            $isNumber = ctype_digit((string) $number);

            if (!$isNumber) {
                return $ret;
            }
        }
```
Where the return $ret is.

**Comment by vinkla** [comment]
Hmm, we have a test for the line you say fail:

https://github.com/ivanakimov/hashids.php/blob/587d2624fd9c2d4cc153cfb8afe28f23152dffa6/tests/HashidsTest.php#L210

As for Mongo IDs, I suggest you take a look at [this issue](https://github.com/ivanakimov/hashids.php/issues/39).
