### ISSUE TITLE
encodeHex() returns empty string under 32-bit PHP

### ISSUE THREAD

**Issue by huyi1985** [ivanakimov/hashids.php#103]
encodeHex() returns empty string under 32-bit PHP

```php
    public function testEncodeHex()
    {
        $userId = '15f574f003337165189cf2cef8318b17';

        self::assertEquals(4, PHP_INT_SIZE);
        $hashids = new Hashids($salt = 'aaaa');
        $encodedUid = $hashids->encodeHex($userId);
        $decodedUid = $hashids->decodeHex($encodedUid);
        self::assertEquals($userId, $decodedUid[0]);
    }
```

```
Failed asserting that two strings are equal.
Expected :'15f574f003337165189cf2cef8318b17'
Actual   :''
```

I think the reason is that `$numbers = trim(chunk_split($str, 12, ' '));`  chunk_split() is called with hard-code parameter **12**, and 12 length hex (48-bit) exceeds PHP_INT_MAX, which is 32-bit under 32-bit PHP.

**Comment by lifewcody** [comment]
Huh, Interesting find, I had my own issue #101 and I think this is why it is not working. XAMPP installs 32bit instead of 64bit so this would align with this issue.

**Comment by vinkla** [comment]
@huyi1985 what is the `Util_Hashids` class?

**Comment by huyi1985** [comment]
@vinkla 
Sorry, I copied my PHPUnit test under our project directly. 
`Util_Hashids` is just an alias for `Hashids\Hashids`. 
Because our old project doesn't utilize Composer, I copy-pasted Hashids code and renamed it.

**Comment by vinkla** [comment]
@huyi1985 thanks for clarifying. Please send us a pull request with a failing test then Travis will pick it up automagically. Thanks!
