### ISSUE TITLE
hashids.php versioning doesn't match versioning on hashids

### ISSUE THREAD

**Issue by Yogarine** [ivanakimov/hashids.php#111]
If I look at the compatibility table at http://hashids.org/php/, it suggests that all implementations stick to the same versioning and should be at `~1.0.0`.

hashids.php has already bumped the major release twice and thus is now at `~3.0.0`, is this an issue?

**Comment by vinkla** [comment]
> ...is this an issue?
We've discussed this internally and decided to bump the PHP package because of breaking changes. There was no way around it if we wanted to benefit from the new features.
