### ISSUE TITLE
different number same result

### ISSUE THREAD

**Issue by galamz** [ivanakimov/hashids.php#114]
**code**
```
       $data[1] = Hashids::encode(215);
        $data[2] = Hashids::encode(1315);

        return $data;
```

**result**
`{"1":"qOWyZxRAb9Y6aJ0waL3gBo4VzPXKlM7N2Q","2":"qOWyZxRAb9Y6aJ0wal3gBo4VzPXKlM7N2Q"}`

**Comment by vinkla** [comment]
Hey @galamz, thanks for reaching! Please open a pull request with failing unit tests.
