### ISSUE TITLE
Cannot be used in CodeIgniter framework

### ISSUE THREAD

**Issue by tyl569** [ivanakimov/hashids.php#120]
When I install hashids in CodeIgniter framework， there is a error `Message: Class 'Hashids\Hashids' not found`, if I want to use it in the CodeIgniter framework, I can't use vender loading it.

**Comment by asadijabar** [comment]
Did you run composer dump-autoload -o ?

**Comment by vinkla** [comment]
Thanks for helping out @asadijabar! 

@tyl569 I would say this isn't related to the Hashids project. See this article about using [CodeIgniter with Composer](https://philsturgeon.uk/php/2012/05/07/composer-with-codeigniter/).
