### ISSUE TITLE
How to go about encoding UUIDs

### ISSUE THREAD

**Issue by vpratfr** [ivanakimov/hashids.php#122]
Hi,

We have UUIDs in our tables. We would like to store a shorter version of the ID for use in URLs.

I understand that you did not want to encode strings, to avoid encouraging bad practises. But we seem to have a valid use case for this.

What would you advise to do to get a short version of our UUIDs for URLs ?

**Comment by ivanakimov** [comment]
There's a `Encode hex instead of numbers` section in README. You can insert the dashes yourself after decoding.
