### ISSUE TITLE
Parameter for controlling hash length to be multiples of n when exceeding minimum length?

### ISSUE THREAD

**Issue by beikeland** [ivanakimov/hashids.php#123]
It would be desirable to essentially group the hash in chunks of say n=4 bytes, initial length of 3n=12, and when exceeding the minimum length of 3n, the new hashes should be 3n+n=16 and so on.

Overall goal is to help make it more human readable and aid in manual entry of id.

xxxx-xxxx-xxxx -> xxxx-xxxx-xxxx-xxxx

**Comment by ivanakimov** [comment]
This can be done outside of Hashids.
