### ISSUE TITLE
Add required extensions to composer?

### ISSUE THREAD

**Issue by davidyell** [ivanakimov/hashids.php#125]
I tried to deploy this and failed due to missing extensions. It's possible to include these in the composer file.

Adding to the require as such

```
"require": {
    "ext-gmp": "*"
    // etc
}
```

**Comment by vinkla** [comment]
Yes, this is possible. Though, we support both `ext-bcmath` and `ext-gmp` and we don't want to enforce either one. It's up to the developer to choose.
