### ISSUE TITLE
when install hashid in laravel mongodb version issue

### ISSUE THREAD

**Issue by dharmendrakumartiwari** [ivanakimov/hashids.php#129]
when install hashid package in laravel mongodb version issue create

**Comment by vinkla** [comment]
> _When a person reviews an Issue Request there should be enough information that they have a good handle of what is being discussed, they don’t need to know or come up with a solution instantly, but nothing about the issue should be mystery meat - [UpThemes](https://upthemes.com/blog/2014/02/writing-useful-github-issues/)_

**Comment by dharmendrakumartiwari** [comment]
i have error when install package
composer require hashids/hashids
Using version ^3.0 for hashids/hashids
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - mongodb/mongodb 1.4.2 requires ext-mongodb ^1.5.0 -> the requested PHP extension mongodb is missing from your system.
    - mongodb/mongodb 1.4.2 requires ext-mongodb ^1.5.0 -> the requested PHP extension mongodb is missing from your system.
    - mongodb/mongodb 1.4.2 requires ext-mongodb ^1.5.0 -> the requested PHP extension mongodb is missing from your system.
    - Installation request for mongodb/mongodb == 1.4.2.0 -> satisfiable by mongodb/mongodb[1.4.2].

  To enable extensions, verify that they are enabled in those .ini files:

**Comment by vinkla** [comment]
This is not an issue with this package. You're missing the `ext-mongodb` extension.
