### ISSUE TITLE
encode(0xffffffff) returns empty string

### ISSUE THREAD

**Issue by ifduyue** [ivanakimov/hashids.php#33]
To reproduce:
```php
<?php

require_once 'vendor/autoload.php';
$hashids = new Hashids\Hashids();
$id = $hashids->encode(0xffffffff);
var_dump($id);

echo "Hashids.php version is ".Hashids\Hashids::VERSION."\n";
```

Output:
```
string(0) ""
Hashids.php version is 1.0.5
```

PHP version:
```bash
$ php -v
PHP 5.6.3 (cli) (built: Nov 16 2014 08:32:30) 
Copyright (c) 1997-2014 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2014 Zend Technologies
```

**Comment by ivanakimov** [comment]
Do you have a 32-bit system? It might be too big of an int to handle, because this works on mine.
Try checking the upper Hashids limit with `$hashids->get_max_int_value();`

https://github.com/ivanakimov/hashids.php#big-numbers

**Comment by ifduyue** [comment]
It's a 64-bit system.  Sorry I did'nt read through the readme. I install php-bcmath and the problem no longer exists.

Thanks for your time.

**Comment by ivanakimov** [comment]
Cool. Glad you got it working.
