### ISSUE TITLE
Any way to increase get_max_int_value() on 32bit systems?

### ISSUE THREAD

**Issue by bgold0** [ivanakimov/hashids.php#34]
I do the following, and I receive this:

    echo $hashids->get_max_int_value(); //2147483647

Is there any alternative means to increase the max int value on a 32bit system? I have fairly large numbers I need to decode and encode.

**Comment by ivanakimov** [comment]
We don't have support for out-of-range int encoding/decoding yet across libraries (although it's planned). But for the meantime, you can simply split the large number and encode it in chunks (and do the reverse - merge upon decoding):

	/* instead of encoding it this way: */
	$hashids->encode(5183105597964288);

	/* encode it in chunks: */
	$hashids->encode(51831055, 97964288);

**Comment by bgold0** [comment]
I appreciate the response and the great class you've created. I suppose I can work with that. Thank you.

**Comment by ivanakimov** [comment]
Glad could help.
