### ISSUE TITLE
Removing Uppercase Characters?

### ISSUE THREAD

**Issue by dinkco** [ivanakimov/hashids.php#49]
I would like my hashids to only contain numbers and lowercase characters, and I see the following character set for generating the ids:

```private $_alphabet = 'abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890';```

Can I override this with a lowercase alphabet only:

```private $_lower_alphabet = 'abcdefghijklmnopqrstuvwxyz1234567890';```

What are the chances of a collision and what is the max limit in the generated ids?

Thanks

**Comment by ivanakimov** [comment]
Yes, you can override it with your own set, but that's not how you do it. Instead, pass it as a parameter to the constructor, as you can see in the README:

```php
$hashids = new Hashids\Hashids('this is my salt', 0, 'abcdefghijklmnopqrstuvwxyz1234567890');
```

There are [no collisions](http://hashids.org/php/#collisions); read the [Big Numbers](https://github.com/ivanakimov/hashids.php#user-content-big-numbers) section for the max integer limit.

**Comment by dinkco** [comment]
Yes, that makes more sense. Thank you for your help.

**Comment by murilolivorato** [comment]
hello ,I want to make lowercase .
I dont know what is happening 

```
FOLDER -
$code            = Hashids::connection('code')->encode(2);

 'code' => [
            'salt' => 'qwertyiopasdfghjkllzxcvbnm123456789',
            'length' => 8,
        ],

```
It is like this the result -

```
xpoNeP90
````

with some words uppercase . how could I make it all lowercase ? thanks

**Comment by king724** [comment]
@murilolivorato it looks like you changed the salt and not the alphabet.
The salt will add a bit uniqueness to your hashids, the alphabet is a list of the characters you want the hashids to be composed of.

To fix your problem, add an 'alphabet' key with the lowercase characters:

```
'code' => [
    'salt' => 'Your-Salt-String',
    'alphabet' => 'qwertyiopasdfghjkllzxcvbnm123456789',
    'length' => 8,
],
```
