### ISSUE TITLE
Can't decode Hash

### ISSUE THREAD

**Issue by interwap** [ivanakimov/hashids.php#53]
Hi, i just downloaded your library, awesome work y'all got going on here. But the problem is the after i encode, i'm unable to decode back to the number and can't really see what i'm doing wrong here. i get an array to string error.

$hashids = new Hashids\Hashids('mysalt',6,'abefghijABCDIJ12789');

		$encoded = $hashids->encode(12);

		echo 'Encoded: '.$encoded.'</br>';

encoding works fine, but to decode back is where the problem lies and i can't say for sure if its a bug.

 $decoded = $hashids->decode($encoded);
but this throws back an error - Notice: Array to string conversion in C:\xampp....oop.php on line 21

What can i do to get this working and all...

**Comment by vinkla** [comment]
Try fetching the first item in the `$decoded[0]` array.

**Comment by interwap** [comment]
worked like a charm! thank you... please try and include this in your readme for us novices. Thanks once again and for the prompt response too

**Comment by vinkla** [comment]
:+1:

**Comment by imzeeshan** [comment]
Hi 
\Hashids::decode() is not working randomly ? Using version 3.1 

Any thoughts ?

**Comment by interwap** [comment]
never had issues with it @imzeeshan any error in particular?

**Comment by imzeeshan** [comment]
Hi @interwap 
Thanks for the quick reply, please see my code below. 

`  $id = \Hashids::encode('098765432'); // o2fXhV
        $numbers = \Hashids::decode($id); // [1, 2, 3]
        print_r($numbers);
        
        $id = \Hashids::encode('l1nB9XnvL6GEzJe'); 
        $numbers = \Hashids::decode($id);
        print_r($numbers);`

The print_r does not show anything, just a blank array.

**Comment by interwap** [comment]
@imzeeshan how did you initialize the class, all can you decode on another page, and not immediately after the encode
