### ISSUE TITLE
duplicates of hashes

### ISSUE THREAD

**Issue by vakorovin** [ivanakimov/hashids.php#57]
Hello! I use Hashids 1.0.6 and received duplicates of hashes.

$hashids = new Hashids ('fabrika', 8);
echo $hashids->encode(53); // 3o1pkgy5
echo $hashids->encode(97); // 3o1pkgy5

**Comment by ivanakimov** [comment]
Hi @vakorovin,

The first encode produces `3o1pkgy5`, while the second produces `3o1pKgy5`.
Notice that `K` is capitalized.

**Comment by vakorovin** [comment]
Oh! Thank you!

**Comment by PurpleBabar** [comment]
Had the same type of issue, helped me a lot. 👍  This link to understand how it could conflict when using unique in sql [on a field that is not case sensitive](http://stackoverflow.com/questions/20311269/doctrine-orm-unique-string-is-not-case-sensitive)
Hope it will help someone else 👍

**Comment by idcmsbeta** [comment]
i hit on this bug ..  QZ and qZ are the same with in mac. When i uploaded my application to server something strange happening.. image not found   since my path /images/qz/zzzzz  .
