### ISSUE TITLE
Generate hashs with just one charactere

### ISSUE THREAD

**Issue by jgrossi** [ivanakimov/hashids.php#59]
Hey!

First of all congrats to the amazing package and thanks a lot for making this open source :-)

Currently is there any way to generate a hash with length of 1? Like integer `1` converting into `m`, for example? I think the smallest hash is from 2 chars length, right?

Thanks for helping.

**Comment by ivanakimov** [comment]
Hi @jgrossi,

Glad you find this useful. Yeah, I don't see any simple way to generate an id with length one. There's a "lottery" character that occupies the first position, so the minimum length would always be two.

You'd have to either gut the code to get rid of that lottery char, or just use basic integer-to-hex conversion (with a bigger alphabet) to achieve that.

**Comment by jgrossi** [comment]
Ok @ivanakimov thanks for the quick reply and support. Best regards.
