### ISSUE TITLE
Alphabet

### ISSUE THREAD

**Issue by alissonlinneker** [ivanakimov/hashids.php#63]
'1234567890abcdefghij' !=  'abcdefghij1234567890'. Why?

```
$hashids = new Hashids\Hashids('this is my salt', 8, '1234567890abcdefghij');
echo $hashids->encode(123);
// Return 428geg85

$hashids = new Hashids\Hashids('this is my salt', 8, 'abcdefghij1234567890');
echo $hashids->encode(123);
// Return d029b657
```

**Comment by ericmartel** [comment]
I would assume because the alphabet is not sorted and it's usage is index based, is this a problem for your usage?

**Comment by ivanakimov** [comment]
What @ericmartel said. It's basic decimal to hex conversion with custom alphabet: http://hashids.org/#how-does-it-work

**Comment by teohhanhui** [comment]
This is really problematic. The "alphabet" by definition should not be ordered.
