### ISSUE TITLE
Best way to generate arbitrary hash

### ISSUE THREAD

**Issue by emersonthis** [ivanakimov/hashids.php#65]
(Great library!)

I'm creating hashes to obfuscate sequential integer IDs in URLs. I don't care what the resulting hash is and I will never need to decode it. The only thing that matters is uniqueness. I would just `encode()` the IDs of the records, but I don't know the ID yet at the time of creating it (and I want this field to be required). My backup plan is to use `time()`, but I see on the readme.md that big numbers can be slow to encode. Is there a better way to do this?

**Comment by ivanakimov** [comment]
1. Are you sure you need to store them in the database (as opposed to generating on the fly)? If yes, you'll need to do an update once you get the numerical id.
2. Are you generating hundreds of thousands ids per second? If no, why are you worrying about speed? This library is already crazy fast.

**Comment by emersonthis** [comment]
Interesting. It didn’t occur to me to generate them on the fly. Is encoding/decoding on the fly performant enough to do in a pretty high volume site? Perhaps 1000 requests per minute?

Thanks!

**Comment by ivanakimov** [comment]
Yes, it is. You could always time it to see if it fits your needs.

Benefits of on-the-fly:
- Can decode back to ID and select directly by it (which is usually already indexed)
- Don't need overhead of maintaining extra column/field in db

Benefits of storing in db:
- Easy to move away to another library later on
- Easy to modify "hashes" to something else

**Comment by emersonthis** [comment]
Thanks!
