### ISSUE TITLE
Public salt

### ISSUE THREAD

**Issue by marcelahne** [ivanakimov/hashids.php#66]
Hi there,

as you didn't declare the variable $_salt as private in the Hashids class the salt is accessible from outside, because a not declared variable is added as a public member when used with $this.

So
$hash = new Hashids('xyz');
echo $hash->_salt;
would print 'xyz'.

This is very critical.

**Comment by vinkla** [comment]
Thanks! Fixed in c926fed1b4f5348e5b2c2c0df12b6d0bdfe6b350

**Comment by marcelahne** [comment]
Thank you :).
Will you provide a minor version update on packagist?
I would like to avoid depending on a development version.

**Comment by vinkla** [comment]
This will be shipped once version 2.0 is released.
