### ISSUE TITLE
Typo in pitfall example?

### ISSUE THREAD

**Issue by rafael-renan-pacheco** [ivanakimov/hashids.php#69]
Hi there!

I guess there is a typo in the pitfall example that can be found here: https://github.com/ivanakimov/hashids.php#pitfalls

This is the example:
```php
use Hashids\Hashids;
$hashids = new Hashids();
$id = $hashids->encode(1);
$hashids->encode($id); // [1]
```

But instead of `$hashids->encode($id)` shouldn't it be `$hashids->decode($id)`?

Best regards,
Rafael Pacheco.

**Comment by vinkla** [comment]
Thanks for pointing it out. Fixed in dadea3210a7d9445c1c9458b0d497d32b0dc0fe1.
