### ISSUE TITLE
Encode over 1000000000 fails

### ISSUE THREAD

**Issue by Pilskalns** [ivanakimov/hashids.php#71]
Hi,

I try to little obfuscate timestamps in seconds, but on Ubuntu PHP 7.0.8-0ubuntu0.16.04.3 (x64) it fails to **encode** numbers which are larger than 1000000000 (exactly, I tested with loops finding breaking point). Also it is able to multiply, substract etc. these numbers.

Oddly, it works on my Windows localhost too PHP 7.0.13 (x64). Both Ubuntu and localhost are truly x64, checked `PHP_INT_MAX` && `PHP_INT_SIZE`.

Have anyone come over this issue?

Here's sample I test:
```php
$hash = new Hashids();

var_dump(	$hash->encode( 1000000000 )	) ; //Works
var_dump(	$hash->encode( 1000000001 )	) ; //Fails
```

Result from above on Ubuntu:
```
string(7) "gn5m6r3" string(0) ""
```
And from Windows:
```
string(7) "gn5m6r3" string(7) "j02pLxl"
```

**Comment by vinkla** [comment]
What version of the package are you using?

**Comment by Pilskalns** [comment]
Looks like version `1.0.6`, I grabbed it with Composer

**Comment by roukmoute** [comment]
Have you try with the last version ?

**Comment by Pilskalns** [comment]
And `sudo apt-get install php7.0-bcmath -y` saves the day. Sorry for confusion guys.

**Comment by ricking06** [comment]
i had this same error bcmath fixed it. any reason why it happend ? 

I wAsTED A DAY
