### ISSUE TITLE
Is it possible to limit output to certain length?

### ISSUE THREAD

**Issue by whimsicaldreamer** [ivanakimov/hashids.php#74]
I am in need for creating short URLs, so the output length needs to be short. How can I limit that and what will be the consequences on doing it?

**Comment by roukmoute** [comment]
The minimum hash length is by default as short as possible.
You can see this [here](https://github.com/ivanakimov/hashids.php/blob/master/src/Hashids.php#L82) :)

**Comment by whimsicaldreamer** [comment]
So its `0` as default :P
Ok, so suppose my id is something like this `1234567` what will be the output length? I was thinking of limiting the output(max hash length) to only 6 chars. Hopefully I am clear.

**Comment by ivanakimov** [comment]
@whimsicaldreamer you can play around with the demo here: http://codepen.io/ivanakimov/pen/bNmExm

You can specify the minimum id length (which works like padding), but not the maximum as you'll overflow it eventually if the number is big enough.
