### ISSUE TITLE
Call to undefined function Hashids\bcdiv()

### ISSUE THREAD

**Issue by JakariaBlaine** [ivanakimov/hashids.php#77]
I was trying to encode id in with Hashids in slim framework. After running the script, I got this error.

**Comment by vinkla** [comment]
Do you've the `ext-bcmath` installed in your environment?

https://secure.php.net/manual/en/book.bc.php

**Comment by JakariaBlaine** [comment]
no...
just installed it and restarted the server.... it worked this time.....
thank you..
