### ISSUE TITLE
v2.0.1 has changed encoded numbers

### ISSUE THREAD

**Issue by nitroshadow** [ivanakimov/hashids.php#78]
`$salt = 'this is my salt';`
`$minHashLength = 12;`
`$hashids = new \Hashids\Hashids($salt, $minHashLength);`

**v2.0.0 result**
`var_dump($hashids->encode(1));` // returns DngB0NV05ev1

**v2.0.1 result**
`var_dump($hashids->encode(1);` // returns B0N444444Vd5

Is this change intended?

**Comment by vinkla** [comment]
I try running your numbers and I get the same result on both versions `DngB0NV05ev1`. Could you please check again just to be sure.

**Comment by nitroshadow** [comment]
I tried again this morning and yes I have now the same result.

Yesterday it was not the case, and to be sure I changed the version of hashids 4 to 5 times by executing the test. A strange bug on my side.

Thank you for checking so fast and sorry for the inconvenience.

**Comment by vinkla** [comment]
No worries.

**Comment by nitroshadow** [comment]
Finally, it seems to be an intermittent problem on my side. When the decoded number is not the right one, I wait a few seconds and I retry and I have the correct encoded number.

I add my info, if it can help to find out what the problem is. For the moment I will stay at v2.0.0.

### The part that gives me the wrong result
https://github.com/ivanakimov/hashids.php/blob/master/src/Hashids.php#L337

**On version 2.0.0 :** i have the correct value returned by $input : '0'.

For a final result of "DngB0NV05ev1"

**On version 2.0.1 :** i have these values returned by $input
* "0.0227272727"
* "0.0005165289"
* "0.0000117392"
* "0.0000002668"
* "0.0000000060"
* "0.0000000001"
* "0.0000000000"

For a final result of "B0N444444Vd5"

### My environment :
Windows 10
EasyPHP Devserver 16.1.1 (64bits)
Apache 2.4.23 x64 - PHP 7.0.13 x64

**Comment by vinkla** [comment]
@jkramarz @ivanakimov any idea about this?

**Comment by jkramarz** [comment]
The previous version was casting all numbers to integers, so it was discarding fractional part (good) and also causing integer overflows in other cases (bad) :-).

When developing I was testing it with default (eq. 0) bc math accuracy, but it seems that your code has bcscale(10) set. In pull request I've explicitly enforced proper (integer) scale for bc functions in this library and added test for your use case, @nitroshadow.

I'm sorry for inconvenience.

**Comment by nitroshadow** [comment]
Thanx for your explication and fast fixes.

I used your test case and https://github.com/ivanakimov/hashids.php/pull/79/commits/e2104ae9f8bfaf19e797b8facfbf7994a5098c03#diff-d09ed0f3077e47603a69c505f8a00859R120 has fixed the issue. Same with bcscale(0).

I also have the 0 by default, but is randomly modified in some request (on my side). With your enforcing it will be fixed.

**Comment by vinkla** [comment]
@nitroshadow thanks for reporting!

@jkramarz thanks again for fixing bugs!

**Comment by vinkla** [comment]
I've released the fix in version 2.0.2
