### ISSUE TITLE
PHP Warning: gmp_add(): Unable to convert variable to GMP

### ISSUE THREAD

**Issue by mxmkmarquette** [ivanakimov/hashids.php#84]
hello i'm using the wordpress plugin based on hashids php, i used it since 2 years, and everything was working good... i had a dedicated server with php5.6 and everything it was need to make the plugin work, but since 2 weeks i switch to a new host.

it come with php7 but since then i got this error into my error_log
PHP Warning: gmp_add(): Unable to convert variable to GMP at line 314 of hashids.php and when i took a look it's this...

$number = $this->_math_functions[‘str’]($this->_math_functions[‘add’]($number, $pos * pow($alphabet_length, ($input_length – $i – 1))));

the wordpress plugin is based on hashids 1.0.6 and i know that a lot's of version have been release since then, i contact ivan and he told me to check if  GMP and BCMath was install on my machine and then to try here that maybe someone could help me... i contact fastcomet and they told me both extension are install and working so how can i fix this up if anyone have an idea.

**Comment by vinkla** [comment]
Try updating to the latest version of Hashids.

**Comment by mxmkmarquette** [comment]
i would love but i'm not a tech savy sorry for saying this but without the plugin i wouldn't know how to integrate hashids to my wordpress... so if you willing to help me no problemo i'll give it a tried without any problem

**Comment by fastcometcloud** [comment]
Hello, Max

Just came across your posting here and decided to follow you up on your post. We can help you with the plugin update. Simply request it via ticket posted to our Tech Support Team, we will create a back up of your website before upgrading the plugin. We are looking forward to hearing back from you.

FastComet Team

**Comment by mxmkmarquette** [comment]
wow seriously you just rock guy and thank you very much for you hard work and stunning tech support.

**Comment by fastcometcloud** [comment]
You can always count on us! Be sure to contact our Techs so we can help you out!

**Comment by ivanakimov** [comment]
Awesome. Closing for now.
