### ISSUE TITLE
No version information in zip file

### ISSUE THREAD

**Issue by f1234k** [ivanakimov/hashids.php#86]
I have tried using hashids in a new Drupal site that I'm building using the [corresponding Drupal module](https://www.drupal.org/project/hashids) but it was referring to an old version of the library (not sure which one exactly but there is a reference to a `lib/Hashids/HashGenerator.php` file). 

Anyway, I have made it work, fixed a couple of issues and I would like to submit it back to the Drupal community and unfortunately I can't find a way to grab the version number from any of the files in the [package](https://github.com/ivanakimov/hashids.php/archive/master.zip) (Drupal libraries require that you specify a regex for them to understand what version of the library they are using; old one looked like this: 
```
    'version arguments' => array(
      'file' => 'lib/Hashids/Hashids.php',
      'pattern' => '/const VERSION = \'([0-9\.]+)\';/',
      'lines' => 20,
```
).

Is this something that can be added back in the library?

Adding it as a comment would work just fine.

**Comment by vinkla** [comment]
We won't provide a version constant in the package since we need to maintain it and it doesn't fullfil a purpose within this library. You could look packages such as [`eloquent/composer-config-reader`](https://github.com/eloquent/composer-config-reader) which lets you read `composer.json` files.

**Comment by f1234k** [comment]
I guess you didn't even read my post; you just picked up random words and made a personal judgement of what I was asking. I did the same with your answer and figured out what the answer to my problem is.

For posterity's sake, the answer to this issue is:

There is version information for the library in the downloadable zip. You can find the version number in the `composer.json` file. Check for the part that looks like this:

```
    "extra": {
        "branch-alias": {
            "dev-master": "2.1-dev"
        }
    }, 
```

**Comment by vinkla** [comment]
> Is this something that can be added back in the library?

We won't provide a version constant in the package since we don't want to maintain the number and it doesn't fullfil a purpose within this library.
