### ISSUE TITLE
Unicode alphabet unsupported?

### ISSUE THREAD

**Issue by blukis** [ivanakimov/hashids.php#87]
Multibyte alphabet (e.g. $alphabet = "😀😃😄😁😆😅😂🤣☺️😊😇🙂🙃😉😌😍😘😗😙") doesn't seem to be supported.

- Perhaps I'm doing something wrong?
- Any chance support could be added?

I tried my hand at modifying to support multibyte alphabet, couldn't get it to materialize.

**Comment by vinkla** [comment]
This is not something we have actively added support for and we probably won't in the future. Thanks for the suggestion though.
