### ISSUE TITLE
Decode issue in an older version (Not tested in new version)

### ISSUE THREAD

**Issue by miranos** [ivanakimov/hashids.php#89]
Hi

I am using the version 0.3.1.

I already used i for many project without any problem, but only to generate URLs.

But now, i integrated it for a big project, where i am required to crypte many values in the same page to protect IDs etc.

It's encrypt them very well, but many times he go wrong, in order to decrypt an ID for example 175 , he decrypt it 75, 166 he decrypt 66, ...etc.

Possible case, is that i have many IDs encrypted in the same page, possible that he encrypt IDs with difference of 100 ?

Any fix ?

Please do not suggest me to go to the new version because i already made many works on the project, and many functions are modified on HashIds in the ne version, like Encrypt become Encode, Decrypt become Decode etc.

The version i am using from 2013 use it like this:

To encrypt:
```
$hashids = new Hashids\Hashids(ENCRYPTION);
$enc = $hashids->encrypt($id);
```
To decrypt:
```
$hashids = new Hashids\Hashids(ENCRYPTION);
$dec = $hashids->decrypt($enc);
$dec = $dec[0];	
```

But if there a trick to integrate the new version without modifing my code will be awesome.

**Comment by miranos** [comment]
So, i finished by locating the problem.

When i encrypt this two values i get the same result (Passed as string):

```
$hashids->encrypt("10"); // r0ZQWLYaM8qJ
$hashids->encrypt("010"); // r0ZQWLYaM8qJ
```
When passed as numbers, this solve the problem:

```
$hashids->encrypt(10); // r0ZQWLYaM8qJ
$hashids->encrypt(010); // 8olpaKka430Z
```
Using salt: `test`

How to fix this in the class directly ?

Is it good to use this class with my project that encode up to 10 ids in one page with salt containing 10 characters ? this not affect server load ?

Thank's.

**Comment by milesich** [comment]
There is nothing to fix here.  10 and 010 are not the same number so you cannot get the same result.

```
 10 // decimal number 
010 // octal number (equivalent to 8 decimal)
```
More about integers in PHP http://php.net/manual/en/language.types.integer.php

**Comment by vinkla** [comment]
Thanks for helping out @milesich!

**Comment by miranos** [comment]
@milesich Yes i know is not same numbers.

I already noticied that when the values passed as String between " ", the class return the same encryption.

When passed directly as numbers without " ", this one encrypt them correctly.
