### ISSUE TITLE
Hashids 1.0.0 PHP does not match JS 1.0.0

### ISSUE THREAD

**Issue by LukeMadhanga** [ivanakimov/hashids.php#93]
On our webservers, we use Python and PHP Hashids @ version 1.0.0

I recently implemented a lambda script (nodejs) that implements Hashids (also @ version 1.0.0). I can confirm that the PHP and JS versions are generating different ids:

[200, 200] (PHP: LLRH3m, JS: LLRs3m)
[50, 50] (The same in both)
[100, 100] (PHP: Nm3FDL, JS: Nm3iDL)

I'm using a custom 30 character alphabet (I can privately send this), and a 20 character salt.

I cannot update the PHP version as it is in use across a huge system.

Environment:
PHP 5.5.22
CentOS 6.6 Final
GMP installed

**EDIT**
I can confirm that the problem occurs *only* when using a custom alphabet. My alphabet is in the form /[a-zA-Z0-9]/

**EDIT 2**
As I'm no longer using the custom alphabet, here it is:
> aBcDeFgHiJkLmNoPqRsTuVwXyZzb83

**Comment by vinkla** [comment]
@LukeMadhanga thanks for reporting. Have you tried running this against the latest version (2.0)?

**Comment by LukeMadhanga** [comment]
@vinkla I have not tried against v2 as I cannot upgrade the PHP version because of backwards compatibility (unless you can tell me that it is backwards compatible)

**Comment by vinkla** [comment]
Okay, I'll go ahead and close this then. We've pushed a lot of fixes in version 2.0.
