### ISSUE TITLE
Call to undefined function Hashids\bcmul()

### ISSUE THREAD

**Issue by WeeHong** [ivanakimov/hashids.php#94]
Hi, I am occurring an issue on Ubuntu 17.04 for this error.

I am using PHP 7.1.0+

May I know how to rectify this issue?

I tried `yum install bcmath` but it show the repo is not longer exists.

Thanks.

**Comment by vinkla** [comment]
Try running the following command:

```sh
sudo apt-get install php-bcmath
```
