### ISSUE TITLE
hashids stopped encoding long string

### ISSUE THREAD

**Issue by ctf0** [ivanakimov/hashids.php#96]
am using current system time to make sure the created ids never collide 
```php
system('date +%s%N')
```

but recently the lib stopped working and started to give empty string instead, ex.
```php
Hashids::encode(1508058326172617500) // 20 digits
```
will give `""`, but if we reduced the number
```php
Hashids::encode(150805832) // 9 digits
```
it will work `"bzeoONEa"`

any reason why this is happening ?

btw testing the same long number on https://codepen.io/ivanakimov/pen/bNmExm works

**Comment by vinkla** [comment]
@ctf0 are you using the default configuration (alphabet, salt, length)?

**Comment by ctf0** [comment]
```php
'main' => [
            'salt'     => 'domain-name',
            'length'   => '8',
            'alphabet' => 'abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890',
        ],
```

**Comment by vinkla** [comment]
What version of this package are you using?

**Comment by ctf0** [comment]
the project still on laravel v5.3 and the package version is v2.4.0

**Comment by Nyholm** [comment]
Could you provide a PR with a unit test that shows this issue? It would be way easier to debug.

**Comment by ctf0** [comment]
@Nyholm i understand, but its not possible atm, anyway i've fixed it by using `uniqid()` in place when the encode fail.

**Comment by kgrsajid** [comment]
I am having the exact same issue. So I am guessing this issue is not resolved yet!
