### ISSUE TITLE
convert string

### ISSUE THREAD

**Issue by alihossein** [ivanakimov/hashids.php#98]
hi . thanks for the useful library. 
can I convert my string to  YouTube-like ?? or this package only works with numbers?
for example, i want to generate a short link from one URL.

**Comment by Nyholm** [comment]
Yes you can. You input an integer ID and get an output of any character. You can even decide what alphabet you want to use.

**Comment by ivanakimov** [comment]
No strings, only numbers.
https://github.com/ivanakimov/hashids.php#pitfalls
